"""API Key 配置 API - v0.1.2 新增
- GET  /api/settings/api-key/status   检查 key 是否设置 (返回前缀 + masked)
- POST /api/settings/api-key          设置 key (写 backend/.env)
- POST /api/settings/api-key/test     校验 key 有效性 (调 OpenRouter /auth/key)

设计要点:
- 写 .env 而非 DB, 因为 config 是 Pydantic Settings 在启动时 load
- 用户在前端"系统设置"填 → 自动合并到 .env
- 后端不重启, settings 已加载的 LLM_API_KEY 不变 (本次进程)
- 下次启动.bat 时 .env 生效
"""
import os
import re
import httpx
import logging
from pathlib import Path
from typing import Optional
from pydantic import BaseModel, Field

from fastapi import APIRouter, HTTPException
from app.core.config import settings

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/settings/api-key", tags=["API Key 配置"])


# ===== Pydantic schemas =====

class ApiKeyStatus(BaseModel):
    is_set: bool
    prefix: Optional[str] = None       # sk-or-v1-xx (前 12 字符 + ...)
    source: Optional[str] = None       # "env" or "missing"
    key_length: Optional[int] = None


class ApiKeySetRequest(BaseModel):
    api_key: str = Field(..., min_length=10, max_length=500)


class ApiKeySetResponse(BaseModel):
    success: bool
    message: str
    prefix: str
    env_file: str


class ApiKeyTestResponse(BaseModel):
    ok: bool
    email: Optional[str] = None
    is_free_tier: Optional[bool] = None
    limit: Optional[float] = None
    limit_remaining: Optional[float] = None
    usage: Optional[float] = None
    error: Optional[str] = None
    error_code: Optional[int] = None


# ===== 工具函数 =====

def _env_path() -> Path:
    """backend/.env 绝对路径"""
    return Path(__file__).resolve().parents[2] / ".env"


def _mask_key(key: str) -> str:
    """返回 key 前 12 字符 + '...' (用于展示)"""
    if not key or len(key) < 8:
        return ""
    return key[:12] + "..."


def _validate_key_format(key: str) -> Optional[str]:
    """校验 key 格式, 不合法返回错误信息"""
    key = key.strip()
    if not key:
        return "key 不能为空"
    # OpenRouter key 一般以 sk-or-v1- 开头, 但兼容其他
    if not re.match(r"^[A-Za-z0-9_\-]+$", key):
        return "key 包含非法字符 (只允许字母数字下划线短横线)"
    if len(key) < 20:
        return "key 太短 (至少 20 字符)"
    return None


def _read_env_file() -> dict:
    """读取 backend/.env 到 dict (key 不带引号)"""
    env = {}
    p = _env_path()
    if not p.exists():
        return env
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)=(.*)$', line)
        if m:
            k, v = m.group(1), m.group(2).strip()
            # 去引号
            if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            env[k] = v
    return env


def _write_env_file(env: dict) -> None:
    """把 dict 写回 backend/.env (保持原注释 + 顺序)

    策略:
    - 先读原文件, 保留注释行 + 空行
    - 对每个 KEY=VALUE, 找现有行覆盖, 没找到追加在末尾
    """
    p = _env_path()
    if not p.exists():
        # 全新创建, 用 .env.example 作模板
        example = p.parent / ".env.example"
        if example.exists():
            content = example.read_text(encoding="utf-8")
        else:
            content = "# Generated by v0.1.2 system settings\n"
    else:
        content = p.read_text(encoding="utf-8")

    lines = content.splitlines()
    written_keys = set()
    new_lines = []

    for line in lines:
        stripped = line.strip()
        # 保留注释/空行
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue
        # 是 KEY=VALUE 形式
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)=', stripped)
        if m:
            key = m.group(1)
            if key in env:
                new_lines.append(f"{key}={env[key]}")
                written_keys.add(key)
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    # 追加新 key
    for k, v in env.items():
        if k not in written_keys:
            new_lines.append(f"{k}={v}")

    p.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    logger.info(f"Updated {p}")


# ===== API 端点 =====

@router.get("/status", response_model=ApiKeyStatus)
async def get_key_status():
    """检查 API Key 是否已设置 (返回 masked prefix)"""
    key = settings.LLM_API_KEY
    if not key:
        return ApiKeyStatus(is_set=False, source="missing")
    return ApiKeyStatus(
        is_set=True,
        prefix=_mask_key(key),
        source="env",
        key_length=len(key),
    )


@router.post("", response_model=ApiKeySetResponse)
async def set_api_key(req: ApiKeySetRequest):
    """设置 API Key → 写入 backend/.env

    注意:
    - 当前进程的 settings.LLM_API_KEY 不会立即更新 (Pydantic Settings 已冻结)
    - 下次启动服务时生效
    - 前端会提示用户"重启服务以生效"
    """
    key = req.api_key.strip()
    err = _validate_key_format(key)
    if err:
        raise HTTPException(400, err)

    # 读现有 env, 更新 LLM_API_KEY
    env = _read_env_file()
    env["LLM_API_KEY"] = key
    _write_env_file(env)

    return ApiKeySetResponse(
        success=True,
        message="key 已写入 backend/.env, 重启服务后生效",
        prefix=_mask_key(key),
        env_file=str(_env_path()),
    )


@router.post("/test", response_model=ApiKeyTestResponse)
async def test_api_key(req: ApiKeySetRequest):
    """测试 key 是否有效 (调 OpenRouter /auth/key)"""
    key = req.api_key.strip()
    err = _validate_key_format(key)
    if err:
        raise HTTPException(400, err)

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.get(
                "https://openrouter.ai/api/v1/auth/key",
                headers={"Authorization": f"Bearer {key}"},
            )
        if r.status_code == 200:
            data = r.json().get("data", {})
            return ApiKeyTestResponse(
                ok=True,
                email=data.get("email"),
                is_free_tier=data.get("is_free_tier"),
                limit=data.get("limit"),
                limit_remaining=data.get("limit_remaining"),
                usage=data.get("usage"),
            )
        else:
            return ApiKeyTestResponse(
                ok=False,
                error_code=r.status_code,
                error=f"OpenRouter 返回 {r.status_code}: {r.text[:200]}",
            )
    except httpx.ConnectError as e:
        return ApiKeyTestResponse(ok=False, error=f"连不上 OpenRouter: {e}")
    except Exception as e:
        logger.error(f"API key test failed: {e}")
        return ApiKeyTestResponse(ok=False, error=str(e))


@router.delete("")
async def clear_api_key():
    """清空 API Key (从 .env 移除 LLM_API_KEY 行)

    用户想完全重新配置时用
    """
    p = _env_path()
    if not p.exists():
        return {"success": True, "message": ".env 不存在, 无需清理"}

    lines = p.read_text(encoding="utf-8").splitlines()
    new_lines = [l for l in lines if not re.match(r"^LLM_API_KEY\s*=", l)]
    p.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    return {"success": True, "message": "LLM_API_KEY 已从 .env 移除, 重启服务后生效"}